version: '3'
services:
  timeserver:
    image: ronaldtanner/timesystem-server:latest
    volumes:
      - "./tmp:/tmp"
  client:
    image: ronaldtanner/timesystem-client:latest
    depends_on:
      - timeserver
    command: "--timeserver=timeserver"
