server:
    image: ronaldtanner/timesystem-server
    volumes:
      - "./tmp:/tmp"
client:
    image: ronaldtanner/timesystem-client
    links:
      - server
    environment:
      TIMESERVER: server
